workflows:
  version: 2
  node-multi-build:
    jobs:
      - node-v8
      - node-v10
      - node-latest
  schedule:
    jobs:
      - update-dependencies
    triggers:
      - schedule:
          cron: "0 0 * * 2" # On every Tuesday 09:00 (JST)
          filters:
            branches:
              only:
                - master

version: 2
jobs:
  base: &base
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run lint
      - run: npm test
      - run: bash <(curl -s https://codecov.io/bash)

  node-v8:
    <<: *base
    docker:
      - image: node:8
  node-v10:
    <<: *base
    docker:
      - image: node:10
  node-latest:
    <<: *base
    docker:
      - image: node:latest
  update-dependencies:
    <<: *base
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: npm install
      - run: npx hothouse
