name: Lint and Test
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/checkout@v1
      - run: node -v
      - run: npm -v

      - run: npm i
      - run: npm run lint
      - run: npm test
      - run: bash <(curl -s https://codecov.io/bash)
