name: Update Dependencies
on:
  schedule:
    - cron: "0 0 * * 2" # On every Tuesday 09:00 (JST)

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/checkout@v1
      - run: node -v
      - run: npm -v

      - run: npm i
      - run: npx hothouse
